### PR TITLE
isMajor bugfix and refactored readSubtree!

### LINKED ISSUE #44: isMajor not correct after reading a network
## example 1: both minor

In the example below, the γ's don't sum up to 1.0 and `isMajor` is not set accordingly:
```julia
using PhyloNetworks
net21 = readTopology("(A,((B,#H1),(C,(D)#H1:::0.2)));")
printEdges(net21)
```
we get get this output, where (D) is missing in the parenthetical description, last line:
```
PhyloNetworks.HybridNetwork, Rooted Network
9 edges
9 nodes: 4 tips, 1 hybrid nodes, 4 internal tree nodes.
tip labels: A, B, C, D
(A,((B,#H1),(C,#H1:::0.2)));
```
It's because both hybrid edges are set to minor, which causes `writeTopology` to not descend below the hybrid edge:

```julia
julia> printEdges(net21)
Edge	Node1	Node2	InCycle	containRoot	istIdentitiable	Length	isHybrid	Gamma	isMajor
1	1	-2	-1	true		false		NA	false		1.0	true
2	2	-4	-1	true		false		NA	false		1.0	true
3	-4	3	-1	false		false		NA	true		-1.0	false
4	-4	-3	-1	true		true		NA	false		1.0	true
5	4	-5	-1	true		false		NA	false		1.0	true
6	5	3	-1	true		false		NA	false		1.0	true
7	3	-5	-1	false		true		NA	true		0.2	false
8	-5	-3	-1	true		true		NA	false		1.0	true
9	-3	-2	-1	true		true		NA	false		1.0	true
```
The γ's aren't in sync, so it's a worry for deleting hybrid edges below some threshold:
```julia
julia> deleteHybridThreshold!(net21,0.5) |> writeTopology
"(A,((B,D),C));"

julia> printEdges(net21)
Edge	Node1	Node2	InCycle	containRoot	istIdentitiable	Length	isHybrid	Gamma	isMajor
1	1	-2	-1	true		false		NA	false		1.0	true
2	2	-4	-1	true		false		NA	false		1.0	true
4	-4	-3	-1	true		true		NA	false		1.0	true
5	4	-3	-1	true		false		NA	false		1.0	true
6	5	-4	-1	true		false		NA	false		1.0	true
9	-3	-2	-1	true		true		NA	false		1.0	true
```
## example 2: both major

Another case with a similar bug: here the γ's are correct (because good input), but both are 0.5 and both hybrid edges are turned major. The one near the leaf node should be made minor:

```julia
julia> net22 = readTopology("(A,((B,#H1:::0.5),(C,(D)#H1:::0.5)));")
```
we get this, where the newick format is incorrect because `writeTopology` descend below the hybrid edge twice, once for each hybrid edge (both major), so `(D)` appears twice:
```
PhyloNetworks.HybridNetwork, Rooted Network
9 edges
9 nodes: 4 tips, 1 hybrid nodes, 4 internal tree nodes.
tip labels: A, B, C, D
(A,((B,(D)#H1:::0.5),(C,(D)#H1:::0.5)));
```

This could be quite dangerous with multiple hybrids. Now to see that both hybrid edges are major, and that it causes an error if we want to delete the hybrid:

```julia
julia> printEdges(net22)
Edge	Node1	Node2	InCycle	containRoot	istIdentitiable	Length	isHybrid	Gamma	isMajor
1	1	-2	-1	true		false		NA	false		1.0	true
2	2	-4	-1	true		false		NA	false		1.0	true
3	-4	3	-1	false		false		NA	true		0.5	true
4	-4	-3	-1	true		true		NA	false		1.0	true
5	4	-5	-1	true		false		NA	false		1.0	true
6	5	3	-1	true		false		NA	false		1.0	true
7	3	-5	-1	false		true		NA	true		0.5	true
8	-5	-3	-1	true		true		NA	false		1.0	true
9	-3	-2	-1	true		true		NA	false		1.0	true

julia> deleteHybridThreshold!(net22,0.5);
ERROR: type Void has no field gamma
 in deleteHybridThreshold!(::PhyloNetworks.HybridNetwork, ::Float64) at /Users/ane/.julia/v0.5/PhyloNetworks/src/compareNetworks.jl:233
```

## checks to add?

To me, it looks like `readTopology` should comply with this:
-  if γ1=γ2 (=0.5 or whatever other value), do *not* set both `isMajor` to true.
-  if γ1 and γ2 < 0.5, do *not* set both `isMajor` to false (minor).
- select the leaf to be minor if both γ's are missing, or both are equal
- re-scale the γ's if their sum is not approximatively 1.0

These things are done in `cleanAfterReadAll!(net,leaveRoot)` inside  `readTopologyUpdate`, but not in `readTopology`.

To fix this issue, it might be also safe to check `setGamma()`. Currently, this function sets `isMajor=true` for γ>0.5 or γ>=0.5. This behavior might need to be changed to *not* update `isMajor` if γ=0.5 (approximately).

### PR DESCRIPTION
**Pull request by ChristianBorst**
This PR resolves #44.

I refactored readSubtree! to remove repeated code segments and improve readability through inline'd helper functions (inline'd to avoid the overhead of a function call).

Both cases of the isMajor bug were caused by two lines of setGamma! only executed when the read parameter was true. I wrote the bugfix code in one of the new helper methods for readSubtree! (named parseEdgeData!) and completely removed the call to setGamma! PhyloNetworks/test/test_isMajor.jl is a new test file which checks for both cases of the isMajor bug.

Additionally, I removed the read parameter from setGamma! because it was only used in a handful of places and fixed the calls which used the read parameter.

### CODE REVIEW

File: src/auxiliary.jl [hunk 1]
```diff
@@ -841,40 +839,35 @@ function setGamma!(edge::Edge, new_gamma::Float64, changeOther::Bool, read::Bool
...
+    elseif(edges[2].hybrid && !edges[1].hybrid)
+        ind = 2
+    else
+        error("strange hybrid node $(node.number) with only one hybrid edge or with three hybrid edges")
+    end
+    if(changeOther)
+        if(!approxEq(new_gamma,0.5))
+            edge.gamma = new_gamma;
+            edge.isMajor = (new_gamma>0.5) ? true : false
+            edges[ind].gamma = 1 - new_gamma;
```
Comment (cecileane) [inline src/auxiliary.jl]: On this line and in other places, could `1` or `0` be replaced by `1.0` or `0.0`? This ensures type consistency, and helps the compiler I guess. I will try to comment briefly on other instances that I spotted.

File: src/auxiliary.jl [hunk 2]
```diff
@@ -841,40 +839,35 @@ function setGamma!(edge::Edge, new_gamma::Float64, changeOther::Bool, read::Bool
...
+            edges[ind].isMajor = (new_gamma<0.5) ? true : false
+        else #new gamma is 0.5
+            edge.gamma = new_gamma
+            edge.isMajor = true
+            edges[ind].gamma = 1 - new_gamma
```
Comment (cecileane) [inline src/auxiliary.jl]: 1 to 1.0 here

File: test/test_isMajor.jl [hunk 3]
```diff
@@ -0,0 +1,20 @@
+@testset "readTopology Hybrid Node isMajor Tests" begin
+	# n1 previously failed: both hybrid parent edges were minor
+	n1 = readTopology("(A,((B,#H1),(C,(D)#H1:::0.2)));")
+	hybridParents = [x for x in n1.hybrid[1].edge if x.hybrid]
+	# Exclusive or to check exactly one parent edge is major
+	@test hybridParents[1].isMajor ^ !hybridParents[2].isMajor
+	# Gammas must sum to 1 and be non-negative for hybrids
+	@test hybridParents[1].gamma + hybridParents[2].gamma == 1
```
Comment (cecileane) [inline test/test_isMajor.jl]: here and lines below: 1 to 1.0 or 0 to 0.0. No big deal, it's just a test file...
